DROP TABLE IF EXISTS endpoint_hits;

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app    character varying(255) NOT NULL,
    uri   character varying(255) NOT NULL,
    ip   character varying(25),
    insert_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (hit_id)
);